"""Write crates/store/tests/surrealql_parses.rs from queries.json. Whole-file write, never a splice:
a query literal can itself contain `];`, which is what broke the first attempt."""
import json, sys

qs = json.load(open(sys.argv[1]))
out = sys.argv[2]

def rs(s):
    # `r#"..."#` cannot hold `"#`; skip such a literal rather than emit invalid Rust.
    return None if '"#' in s else 'r#"' + s + '"#'

rows, skipped, unverifiable = [], 0, 0
for q in qs:
    # A literal the extractor could not fully resolve proves nothing either way — see the note in
    # `extract_ql.py`. Counting it as a failure would be a false alarm; counting it as a pass would
    # be a false assurance. It is left out, and reported.
    if q.get('unverifiable'):
        unverifiable += 1
        continue
    vs = [rs(v) for v in q['variants']]
    site = rs(q['where'])
    if site is None or any(v is None for v in vs):
        skipped += 1
        continue
    seen, uniq = set(), []
    for v in vs:
        if v not in seen:
            seen.add(v); uniq.append(v)
    rows.append(f'    ({site}, &[{", ".join(uniq)}]),')

header = '''//! Every SurrealQL literal in the tree, parsed by SurrealDB 3's own parser.
//!
//! A green `cargo build` proves nothing about SurrealQL: queries are strings, so a rename like
//! `type::thing` -> `type::record`, or a clause that moved like `FLEXIBLE TYPE x` -> `TYPE x
//! FLEXIBLE`, compiles perfectly and only fails when the query first executes. This closes that gap
//! statically -- `surrealdb_core::syn::parse` is the parser the engine itself runs, so a literal
//! that passes here cannot fail at runtime for syntax.
//!
//! It does NOT check semantics: a parseable query can still name a field that no longer exists or
//! return a different shape. That is the rest of the suite's job.
//!
//! Scope: SurrealQL only. `federation`, `prql` and the pack exporters emit Postgres/SQLite, which a
//! SurrealQL parser rightly rejects; the generator excludes them by path and by shape.
//!
//! Generated by `scripts/extract_ql.py` -- regenerate when queries change. The generator resolves
//! `const X: &str = "..."` placeholders to their real text, so a column list stays a column list;
//! anything still unresolved is tried as a bare identifier, a number and a quoted string, and the
//! literal passes if ANY of those parses.

'''
body = '\n'.join(rows)
footer = '''

#[test]
fn every_surrealql_literal_parses_under_surrealdb_3() {
    let mut failures = Vec::new();
    for (site, variants) in QUERIES {
        let mut last = String::new();
        let ok = variants.iter().any(|sql| match surrealdb_core::syn::parse(sql) {
            Ok(_) => true,
            Err(e) => {
                last = e.to_string();
                false
            }
        });
        if !ok {
            failures.push(format!("{site}\\n    {}\\n    {last}", variants[0]));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} SurrealQL literals do not parse under SurrealDB 3:\\n\\n{}",
        failures.len(),
        QUERIES.len(),
        failures.join("\\n\\n")
    );
}
'''
# The CORPUS is data, not hand-written code, so it lands under `tests/generated/` — the path the
# FILE-LAYOUT gate excludes (a 1400-line table of literals is not a file anyone "splits"), and a
# subdirectory cargo does not pick up as a test target of its own. The test file itself stays a
# thin includer, small enough to read.
import os
gen_dir = os.path.join(os.path.dirname(out), 'generated')
os.makedirs(gen_dir, exist_ok=True)
corpus = os.path.join(gen_dir, 'surrealql_corpus.rs')
open(corpus, 'w').write(
    '// GENERATED by rust/scripts/gen_surrealql_test.py — do not edit by hand.\n'
    'const QUERIES: &[(&str, &[&str])] = &[\n' + body.lstrip('\n') + '];\n')
open(out, 'w').write(header + '\ninclude!("generated/surrealql_corpus.rs");\n' + footer)
print(f"skipped {unverifiable} unverifiable (unresolved placeholders)")
print(f"wrote {len(rows)} literals ({skipped} skipped: literal contains `\"#`)")
