//! Every SurrealQL literal in the tree, parsed by SurrealDB 3's own parser.
//!
//! A green `cargo build` proves nothing about SurrealQL: queries are strings, so a rename like
//! `type::thing` -> `type::record`, or a clause that moved like `FLEXIBLE TYPE x` -> `TYPE x
//! FLEXIBLE`, compiles perfectly and only fails when the query first executes. This closes that gap
//! statically -- `surrealdb_core::syn::parse` is the parser the engine itself runs, so a literal
//! that passes here cannot fail at runtime for syntax.
//!
//! It does NOT check semantics: a parseable query can still name a field that no longer exists or
//! return a different shape. That is the rest of the suite's job.
//!
//! Scope: SurrealQL only. `federation`, `prql` and the pack exporters emit Postgres/SQLite, which a
//! SurrealQL parser rightly rejects; the generator excludes them by path and by shape.
//!
//! Generated by `scripts/extract_ql.py` -- regenerate when queries change. The generator resolves
//! `const X: &str = "..."` placeholders to their real text, so a column list stays a column list;
//! anything still unresolved is tried as a bare identifier, a number and a quoted string, and the
//! literal passes if ANY of those parses.

include!("generated/surrealql_corpus.rs");

#[test]
fn every_surrealql_literal_parses_under_surrealdb_3() {
    let mut failures = Vec::new();
    for (site, variants) in QUERIES {
        let mut last = String::new();
        let ok = variants
            .iter()
            .any(|sql| match surrealdb_core::syn::parse(sql) {
                Ok(_) => true,
                Err(e) => {
                    last = e.to_string();
                    false
                }
            });
        if !ok {
            failures.push(format!("{site}\n    {}\n    {last}", variants[0]));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} SurrealQL literals do not parse under SurrealDB 3:\n\n{}",
        failures.len(),
        QUERIES.len(),
        failures.join("\n\n")
    );
}
