//! Cargo `target/` dirs — the big one (196 GB across 5 dirs on this box).
//!
//! A target dir is identified structurally, never by name alone: a dir called
//! `target` counts only if its parent holds a `Cargo.toml`. That is what stops us
//! from proposing to delete `src/target/` in some unrelated project, or a vendored
//! `target` fixture. `cargo build` regenerates the real thing, which is exactly why
//! it is safe to delete and why it is worth this much disk.
//!
//! Nested targets are not double-counted: once a target dir is found we do not
//! descend into it, so `target/debug/build/*/out/target` never appears.

use std::path::Path;

use walkdir::WalkDir;

use crate::candidate::Candidate;
use crate::reclaimer::{Reclaimer, ScanCtx};
use crate::size::measure;

/// How deep below a root to look for projects. Deep enough for
/// `~/code/rust/<repo>/rust/target`, shallow enough not to crawl the world.
const MAX_DEPTH: usize = 6;

pub struct CargoTarget;

pub const ID: &str = "cargo-target";

impl Reclaimer for CargoTarget {
    fn id(&self) -> &'static str {
        ID
    }

    fn describe(&self) -> &'static str {
        "Rust build artifacts (target/) — regenerated by `cargo build`"
    }

    fn scan(&self, ctx: &ScanCtx) -> anyhow::Result<Vec<Candidate>> {
        let mut found = Vec::new();

        for root in &ctx.roots {
            let mut walker = WalkDir::new(root)
                .follow_links(false)
                .max_depth(MAX_DEPTH)
                .into_iter();

            while let Some(entry) = walker.next() {
                let Ok(entry) = entry else { continue };
                if !entry.file_type().is_dir() {
                    continue;
                }
                if !is_cargo_target(entry.path()) {
                    continue;
                }
                // Don't walk into it twice: once as a candidate, once as a subtree.
                walker.skip_current_dir();
                found.push(Candidate::new(
                    ID,
                    entry.path().to_path_buf(),
                    project_label(entry.path()),
                    measure(entry.path()),
                ));
            }
        }

        found.sort_by(|a, b| b.bytes.cmp(&a.bytes));
        Ok(found)
    }

    fn reclaim(&self, candidate: &Candidate) -> anyhow::Result<u64> {
        // Re-verify at delete time. The scan may be minutes (or a cron interval) old,
        // and `candidate.path` arrives from a state file the tray wrote. We refuse to
        // delete anything that is not, right now, a real cargo target dir.
        if !candidate.path.exists() {
            return Ok(0); // already gone — idempotent, not an error
        }
        anyhow::ensure!(
            is_cargo_target(&candidate.path),
            "refusing to delete {}: not a cargo target dir (no Cargo.toml beside it)",
            candidate.path.display()
        );

        let freed = measure(&candidate.path).bytes;
        std::fs::remove_dir_all(&candidate.path)?;
        Ok(freed)
    }
}

/// A dir is a cargo target iff it is named `target` and its parent has a `Cargo.toml`.
fn is_cargo_target(dir: &Path) -> bool {
    if dir.file_name().and_then(|n| n.to_str()) != Some("target") {
        return false;
    }
    dir.parent()
        .map(|p| p.join("Cargo.toml").is_file())
        .unwrap_or(false)
}

/// A name you'd recognise: the enclosing git repo ("lb", "cc-app", "ems").
///
/// The parent dir name alone is not it. The three biggest targets on this box live at
/// `<repo>/rust/target`, so the parent is literally `rust` for all of them — three
/// 90-GB rows all labelled "rust" tell you nothing about which is which. The repo
/// root is the unit you actually think in, so walk up to the nearest `.git` and use
/// that. Falls back to the parent dir name outside a repo.
fn project_label(target_dir: &Path) -> String {
    let parent = target_dir.parent();

    let repo = parent
        .into_iter()
        .flat_map(|p| p.ancestors())
        .find(|a| a.join(".git").exists());

    repo.or(parent)
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("?")
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// Build a fake project tree: <root>/<name>/{Cargo.toml, target/<junk>}
    fn project(root: &Path, name: &str, junk_bytes: usize) -> PathBuf {
        let dir = root.join(name);
        let target = dir.join("target");
        std::fs::create_dir_all(&target).unwrap();
        std::fs::write(dir.join("Cargo.toml"), "[package]\nname='x'\n").unwrap();
        std::fs::write(target.join("artifact.rlib"), vec![0u8; junk_bytes]).unwrap();
        target
    }

    fn ctx(root: &Path) -> ScanCtx {
        ScanCtx {
            roots: vec![root.to_path_buf()],
            now_secs: crate::size::now_secs(),
        }
    }

    /// The three biggest targets on this box are all `<repo>/rust/target` — the
    /// parent dir name would label every one of them "rust".
    #[test]
    fn labels_a_target_with_its_git_repo_not_the_parent_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("cc-app");
        std::fs::create_dir_all(repo.join(".git")).unwrap();
        project(&repo, "rust", 1024); // -> cc-app/rust/target

        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].label, "cc-app", "not \"rust\"");
    }

    #[test]
    fn falls_back_to_the_parent_dir_name_outside_a_git_repo() {
        let tmp = tempfile::tempdir().unwrap();
        project(tmp.path(), "loose-proj", 1024);

        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();
        assert_eq!(found[0].label, "loose-proj");
    }

    #[test]
    fn finds_a_real_target_and_measures_it() {
        let tmp = tempfile::tempdir().unwrap();
        project(tmp.path(), "myproj", 4096);

        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].label, "myproj");
        assert_eq!(found[0].kind, ID);
        assert_eq!(found[0].bytes, 4096);
    }

    /// The false-positive guard: `target` without a sibling Cargo.toml is NOT ours.
    #[test]
    fn ignores_a_target_dir_with_no_cargo_toml_beside_it() {
        let tmp = tempfile::tempdir().unwrap();
        let decoy = tmp.path().join("webapp/target");
        std::fs::create_dir_all(&decoy).unwrap();
        std::fs::write(decoy.join("bundle.js"), vec![0u8; 4096]).unwrap();

        assert!(CargoTarget.scan(&ctx(tmp.path())).unwrap().is_empty());
    }

    #[test]
    fn does_not_report_a_target_nested_inside_a_target() {
        let tmp = tempfile::tempdir().unwrap();
        let outer = project(tmp.path(), "outer", 1024);
        // A build script that vendored its own crate + target inside the outer target.
        let inner = outer.join("debug/build/dep-1234/out/inner");
        std::fs::create_dir_all(inner.join("target")).unwrap();
        std::fs::write(inner.join("Cargo.toml"), "[package]\nname='i'\n").unwrap();

        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();
        assert_eq!(found.len(), 1, "only the outer target is a candidate");
        assert_eq!(found[0].label, "outer");
    }

    #[test]
    fn biggest_first() {
        let tmp = tempfile::tempdir().unwrap();
        project(tmp.path(), "small", 1024);
        project(tmp.path(), "huge", 64 * 1024);
        project(tmp.path(), "medium", 8 * 1024);

        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();
        let labels: Vec<_> = found.iter().map(|c| c.label.as_str()).collect();
        assert_eq!(labels, ["huge", "medium", "small"]);
    }

    #[test]
    fn reclaim_deletes_the_target_and_keeps_the_source() {
        let tmp = tempfile::tempdir().unwrap();
        let target = project(tmp.path(), "myproj", 4096);

        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();
        let freed = CargoTarget.reclaim(&found[0]).unwrap();

        assert_eq!(freed, 4096);
        assert!(!target.exists(), "target/ is gone");
        assert!(
            target.parent().unwrap().join("Cargo.toml").is_file(),
            "the project itself must survive"
        );
    }

    #[test]
    fn reclaiming_something_already_gone_is_ok_zero() {
        let tmp = tempfile::tempdir().unwrap();
        project(tmp.path(), "myproj", 512);
        let found = CargoTarget.scan(&ctx(tmp.path())).unwrap();

        assert_eq!(CargoTarget.reclaim(&found[0]).unwrap(), 512);
        assert_eq!(
            CargoTarget.reclaim(&found[0]).unwrap(),
            0,
            "second reclaim is idempotent, not an error"
        );
    }

    /// A stale/tampered candidate must not turn into `rm -rf` of an arbitrary path.
    #[test]
    fn refuses_to_delete_a_path_that_is_not_a_target_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let precious = tmp.path().join("precious");
        std::fs::create_dir_all(&precious).unwrap();
        std::fs::write(precious.join("thesis.txt"), b"years of work").unwrap();

        let forged = Candidate {
            kind: ID.into(),
            path: precious.clone(),
            label: "precious".into(),
            bytes: 13,
            last_used_secs: 0,
        };

        assert!(CargoTarget.reclaim(&forged).is_err(), "must refuse");
        assert!(precious.join("thesis.txt").is_file(), "and must not delete");
    }
}
