//! Golden PRQL→SQL tests per dialect + a typed error on malformed PRQL (query scope, testing §0:
//! these are pure unit tests over the real `prqlc` — no mocks). The goldens freeze the compile
//! contract; a `prqlc` bump is a reviewed change with re-frozen goldens. Asserts on normalized SQL
//! (whitespace collapsed) against stable substrings so cosmetic formatter tweaks don't flake — the
//! contract is "compiles to a SELECT against the right table for this dialect", not whitespace.

use lb_prql::{compile, dialect_for_kind, dialect_for_target, Dialect, PrqlError};

/// Collapse runs of whitespace so multi-line `prqlc` output can be matched on content, not layout.
fn norm(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

const ORDERS: &str = "from orders | filter status == \"paid\" | select {id, amount} | sort {-id}";

#[test]
fn generic_platform_compiles_to_select() {
    let sql = norm(&compile(ORDERS, Dialect::Generic).unwrap());
    assert!(sql.starts_with("SELECT "), "generic sql was: {sql}");
    assert!(sql.contains("FROM orders"), "sql was: {sql}");
    assert!(sql.contains("WHERE status = 'paid'"), "sql was: {sql}");
    assert!(sql.contains("ORDER BY id DESC"), "sql was: {sql}");
}

#[test]
fn postgres_dialect_compiles() {
    let sql = norm(&compile(ORDERS, Dialect::Postgres).unwrap());
    assert!(sql.starts_with("SELECT "), "postgres sql was: {sql}");
    assert!(sql.contains("FROM orders"), "sql was: {sql}");
}

#[test]
fn mysql_dialect_compiles() {
    let sql = norm(&compile(ORDERS, Dialect::MySql).unwrap());
    assert!(sql.starts_with("SELECT "), "mysql sql was: {sql}");
    assert!(sql.contains("FROM orders"), "sql was: {sql}");
}

#[test]
fn duckdb_dialect_compiles() {
    let sql = norm(&compile(ORDERS, Dialect::DuckDb).unwrap());
    assert!(sql.starts_with("SELECT "), "duckdb sql was: {sql}");
    assert!(sql.contains("FROM orders"), "sql was: {sql}");
}

#[test]
fn aggregate_group_compiles() {
    let prql = "from readings | group store ( aggregate { avg_temp = average temp } )";
    let sql = norm(&compile(prql, Dialect::Postgres).unwrap());
    assert!(sql.contains("AVG("), "sql was: {sql}");
    assert!(sql.contains("GROUP BY"), "sql was: {sql}");
}

#[test]
fn take_limit_compiles() {
    let sql = norm(&compile("from t | take 10", Dialect::Generic).unwrap());
    assert!(sql.contains("LIMIT 10"), "sql was: {sql}");
}

#[test]
fn malformed_prql_is_typed_error() {
    let bad = "from | select {"; // missing table, unclosed
    let err = compile(bad, Dialect::Generic).unwrap_err();
    assert!(matches!(err, PrqlError::Compile(_)), "got {err:?}");
    assert!(!err.to_string().is_empty());
}

#[test]
fn no_signature_comment_in_output() {
    let sql = compile("from t | take 1", Dialect::Generic).unwrap();
    assert!(
        !sql.contains("Generated by PRQL"),
        "signature leaked: {sql}"
    );
}

#[test]
fn target_platform_is_generic_dialect() {
    assert_eq!(dialect_for_target("platform").unwrap(), Dialect::Generic);
}

#[test]
fn target_unknown_is_bad_dialect() {
    let err = dialect_for_target("bogus").unwrap_err();
    assert!(matches!(err, PrqlError::BadDialect(_)), "got {err:?}");
}

#[test]
fn datasource_kinds_map_to_dialects() {
    assert_eq!(dialect_for_kind("postgres").unwrap(), Dialect::Postgres);
    assert_eq!(dialect_for_kind("timescale").unwrap(), Dialect::Postgres);
    assert_eq!(dialect_for_kind("mysql").unwrap(), Dialect::MySql);
    assert_eq!(dialect_for_kind("duckdb").unwrap(), Dialect::DuckDb);
    assert!(matches!(
        dialect_for_kind("oracle").unwrap_err(),
        PrqlError::BadDialect(_)
    ));
}
