//! Catalog rows for the `stats` family's non-windowed half — one row per `register_fn` site in
//! this folder, appended into [`crate::catalog::CATALOG`] via `verbs::stats::CATALOG`. The six
//! windowed rows live in `verbs/window.rs::CATALOG` (same family, two files). Append-only.

use crate::catalog::FnEntry;

#[rustfmt::skip]
pub(crate) const CATALOG: &[FnEntry] = &[
    // ---- center/spread (center.rs) ----
    FnEntry { name: "sum", family: "stats", signature: "sum(a: Array) -> Float",
        description: "Sum of the numeric values (missing skipped; 0.0 for an empty array)." },
    FnEntry { name: "mean", family: "stats", signature: "mean(a: Array) -> Float",
        description: "Arithmetic mean of the numeric values (missing skipped)." },
    FnEntry { name: "median", family: "stats", signature: "median(a: Array) -> Float",
        description: "Median (50th percentile, linear interpolation) of the numeric values." },
    FnEntry { name: "mode", family: "stats", signature: "mode(a: Array) -> Float",
        description: "Most frequent numeric value; ties break to the smallest value." },
    FnEntry { name: "min_of", family: "stats", signature: "min_of(a: Array) -> Float",
        description: "Smallest numeric value in the array." },
    FnEntry { name: "max_of", family: "stats", signature: "max_of(a: Array) -> Float",
        description: "Largest numeric value in the array." },
    FnEntry { name: "range_of", family: "stats", signature: "range_of(a: Array) -> Float",
        description: "Spread of the numeric values (max minus min)." },
    FnEntry { name: "variance", family: "stats", signature: "variance(a: Array) -> Float",
        description: "Sample variance (n-1 denominator) of the numeric values." },
    FnEntry { name: "std_dev", family: "stats", signature: "std_dev(a: Array) -> Float",
        description: "Sample standard deviation (n-1 denominator) of the numeric values." },
    FnEntry { name: "sem", family: "stats", signature: "sem(a: Array) -> Float",
        description: "Standard error of the mean (sample std over sqrt(n))." },
    // ---- quantiles (center.rs) ----
    FnEntry { name: "percentile", family: "stats", signature: "percentile(a: Array, p: Float) -> Float",
        description: "The p-th percentile (0..=100) with linear interpolation between ranks." },
    FnEntry { name: "quantiles", family: "stats", signature: "quantiles(a: Array, ps: Array) -> Array",
        description: "One interpolated percentile per entry of ps (each 0..=100)." },
    FnEntry { name: "iqr", family: "stats", signature: "iqr(a: Array) -> Float",
        description: "Interquartile range (75th minus 25th percentile)." },
    // ---- shape (shape.rs) ----
    FnEntry { name: "skewness", family: "stats", signature: "skewness(a: Array) -> Float",
        description: "Fisher-Pearson skewness g1 (population moments; 0.0 is symmetric)." },
    FnEntry { name: "kurtosis", family: "stats", signature: "kurtosis(a: Array) -> Float",
        description: "Excess kurtosis g2 (population moments; 0.0 matches a normal distribution)." },
    FnEntry { name: "histogram", family: "stats", signature: "histogram(a: Array, bins: Int) -> Array",
        description: "Equal-width histogram over [min, max] as [#{lo, hi, n}, …] (last bucket inclusive)." },
    // ---- normalize (shape.rs) ----
    FnEntry { name: "zscores", family: "stats", signature: "zscores(a: Array) -> Array",
        description: "Positional z-scores against the array's sample mean/std (missing slots stay ())." },
    FnEntry { name: "minmax_scale", family: "stats", signature: "minmax_scale(a: Array) -> Array",
        description: "Positional min-max scaling to [0, 1] (errors when all values are equal)." },
    FnEntry { name: "clip_arr", family: "stats", signature: "clip_arr(a: Array, lo: Float, hi: Float) -> Array",
        description: "Positional clamp of every numeric value into [lo, hi]." },
    FnEntry { name: "rank", family: "stats", signature: "rank(a: Array) -> Array",
        description: "Positional 1-based ascending ranks; ties share their average rank." },
    // ---- relate (relate.rs) ----
    FnEntry { name: "corr", family: "stats", signature: "corr(a: Array, b: Array) -> Float",
        description: "Pearson correlation over positions numeric on both sides (same-length arrays)." },
    FnEntry { name: "spearman", family: "stats", signature: "spearman(a: Array, b: Array) -> Float",
        description: "Spearman rank correlation (Pearson over average ranks)." },
    FnEntry { name: "cov", family: "stats", signature: "cov(a: Array, b: Array) -> Float",
        description: "Sample covariance (n-1 denominator) over pairwise-complete positions." },
    FnEntry { name: "linreg", family: "stats", signature: "linreg(xs: Array, ys: Array) -> Map",
        description: "Least-squares line fit returning #{slope, intercept, r2}." },
    FnEntry { name: "predict", family: "stats", signature: "predict(model: Map, x: Float) -> Float",
        description: "Apply a linreg model map to one x (slope * x + intercept)." },
    FnEntry { name: "forecast_linear", family: "stats", signature: "forecast_linear(a: Array, n: Int) -> Array",
        description: "Fit index-vs-value by least squares and extend the line for the next n positions." },
    // ---- sequence (sequence.rs) ----
    FnEntry { name: "cumsum", family: "stats", signature: "cumsum(a: Array) -> Array",
        description: "Positional running sum (missing slots stay (); the sum carries across gaps)." },
    FnEntry { name: "cummax", family: "stats", signature: "cummax(a: Array) -> Array",
        description: "Positional running maximum (missing slots stay ())." },
    FnEntry { name: "cummin", family: "stats", signature: "cummin(a: Array) -> Array",
        description: "Positional running minimum (missing slots stay ())." },
    FnEntry { name: "diffs", family: "stats", signature: "diffs(a: Array) -> Array",
        description: "Neighbor differences a[i] - a[i-1] (first slot and any gap-adjacent step are ())." },
    FnEntry { name: "pct_changes", family: "stats", signature: "pct_changes(a: Array) -> Array",
        description: "Neighbor fractional change (a[i] - a[i-1]) / a[i-1] (() when undefined)." },
    FnEntry { name: "shift_arr", family: "stats", signature: "shift_arr(a: Array, n: Int) -> Array",
        description: "Shift values n positions (positive right, negative left), filling vacated slots with ()." },
    // ---- missing (missing.rs) ----
    FnEntry { name: "dropna", family: "stats", signature: "dropna(a: Array) -> Array",
        description: "Compact to the numeric values only, dropping every missing entry." },
    FnEntry { name: "fillna", family: "stats", signature: "fillna(a: Array, v: Float) -> Array",
        description: "Replace every missing entry with the number v (positions preserved)." },
    FnEntry { name: "ffill", family: "stats", signature: "ffill(a: Array) -> Array",
        description: "Forward-fill gaps with the last numeric value (leading gaps stay ())." },
    FnEntry { name: "bfill", family: "stats", signature: "bfill(a: Array) -> Array",
        description: "Backward-fill gaps with the next numeric value (trailing gaps stay ())." },
    FnEntry { name: "interp_linear", family: "stats", signature: "interp_linear(a: Array) -> Array",
        description: "Linearly interpolate interior gaps between numeric neighbors (edge gaps stay ())." },
    // ---- outliers (select.rs) ----
    FnEntry { name: "outliers_iqr", family: "stats", signature: "outliers_iqr(a: Array, k: Float) -> Array",
        description: "Indices outside the Tukey fences [q1 - k*iqr, q3 + k*iqr]." },
    FnEntry { name: "outliers_z", family: "stats", signature: "outliers_z(a: Array, thr: Float) -> Array",
        description: "Indices whose absolute sample z-score exceeds thr." },
    FnEntry { name: "is_anomaly", family: "stats", signature: "is_anomaly(a: Array, x: Float, thr: Float) -> Bool",
        description: "Whether x lies more than thr sample standard deviations from the array's mean." },
    // ---- selection (select.rs) ----
    FnEntry { name: "top_k", family: "stats", signature: "top_k(a: Array, k: Int) -> Array",
        description: "The k largest numeric values, descending (all of them when k exceeds the count)." },
    FnEntry { name: "bottom_k", family: "stats", signature: "bottom_k(a: Array, k: Int) -> Array",
        description: "The k smallest numeric values, ascending (all of them when k exceeds the count)." },
    FnEntry { name: "argmax", family: "stats", signature: "argmax(a: Array) -> Int",
        description: "Index (into the original array) of the first largest numeric value." },
    FnEntry { name: "argmin", family: "stats", signature: "argmin(a: Array) -> Int",
        description: "Index (into the original array) of the first smallest numeric value." },
    FnEntry { name: "sample", family: "stats", signature: "sample(a: Array, n: Int, seed: Int) -> Array",
        description: "n elements drawn without replacement using the mandatory seed (deterministic; elements verbatim)." },
    FnEntry { name: "shuffle", family: "stats", signature: "shuffle(a: Array, seed: Int) -> Array",
        description: "Fisher-Yates permutation driven by the mandatory seed (deterministic; elements verbatim)." },
];
