//! Media at the host layer: the chunked upload protocol, serve route, and variant derivation
//! (media scope). Tests the mandatory capability-deny, workspace isolation, resume after dropped
//! chunk, bad checksum, duplicate chunk idempotency, oversize rejection, variant derivation, and
//! ETag. Real store, real caps — no mocks (rule 9). Images are seeded real bytes.

use lb_auth::{mint, verify, Claims, Principal, Role, SigningKey};
use lb_host::{
    chunk_write, media_delete, media_get, media_list, media_serve, media_upload_begin,
    media_upload_commit, MediaError,
};
use lb_store::Store;
use sha2::{Digest, Sha256};

fn principal(sub: &str, ws: &str, caps: &[&str]) -> Principal {
    let key = SigningKey::generate();
    let claims = Claims {
        sub: sub.into(),
        ws: ws.into(),
        role: Role::Member,
        caps: caps.iter().map(|s| s.to_string()).collect(),
        iat: 0,
        exp: u64::MAX,
        constraint: None,
        run_id: None,
    };
    let token = mint(&key, &claims);
    verify(&key, &token, 1).expect("token verifies")
}

const CAPS: &[&str] = &[
    "mcp:media.upload:call",
    "mcp:media.get:call",
    "mcp:media.delete:call",
    "store:media/*:read",
];

fn checksum(bytes: &[u8]) -> String {
    let hash = Sha256::digest(bytes);
    hex(&hash)
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(char::from_digit((b >> 4) as u32, 16).unwrap());
        out.push(char::from_digit((b & 0xf) as u32, 16).unwrap());
    }
    out
}

/// A real 4x4 red PNG generated by the `image` crate (not a hand-crafted byte sequence).
fn tiny_png() -> Vec<u8> {
    let img = image::RgbImage::from_pixel(4, 4, image::Rgb([255, 0, 0]));
    let mut buf = Vec::new();
    image::DynamicImage::ImageRgb8(img)
        .write_to(&mut std::io::Cursor::new(&mut buf), image::ImageFormat::Png)
        .unwrap();
    buf
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn upload_and_serve_image() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "acme", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    // Begin
    let begin = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    let chunks = begin["chunks"].as_u64().unwrap();
    assert_eq!(chunks, 1);

    // Upload chunk 0
    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();

    // Commit
    let commit = media_upload_commit(&store, &p, "acme", &id, 200)
        .await
        .unwrap();
    assert_eq!(commit["ok"], serde_json::json!(true));

    // Serve original
    let served = media_serve(&store, &p, "acme", &id, None).await.unwrap();
    assert_eq!(served.bytes, img);
    assert_eq!(served.mime, "image/png");

    // Serve thumb variant
    let thumb = media_serve(&store, &p, "acme", &id, Some("thumb"))
        .await
        .unwrap();
    assert_eq!(thumb.mime, "image/jpeg");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn duplicate_chunk_is_idempotent() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "acme", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    // Write chunk 0 twice — idempotent.
    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();
    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();

    media_upload_commit(&store, &p, "acme", &id, 200)
        .await
        .unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn bad_checksum_is_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "acme", CAPS);
    let img = tiny_png();

    let begin = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        img.len() as u64,
        "wrong-checksum",
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();

    let err = media_upload_commit(&store, &p, "acme", &id, 200)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::BadChecksum));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn oversize_rejected_at_begin() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "acme", CAPS);

    let err = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        999_999_999_999,
        "checksum",
        None,
        100,
    )
    .await
    .unwrap_err();
    assert!(matches!(err, MediaError::TooLarge));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn serve_not_ready_media_is_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "acme", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    // Don't commit — media is still Uploading.
    let err = media_serve(&store, &p, "acme", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotReady));
}

// ── Mandatory: capability-deny ──────────────────────────────────────────────────────────────

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn denies_upload_without_cap() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:mallory", "acme", &["mcp:media.get:call"]);

    let err = media_upload_begin(&store, &p, "acme", "image/png", 100, "cs", None, 100)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::Denied));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn denies_serve_without_read_cap() {
    let store = Store::memory().await.unwrap();
    // Has upload cap but NOT store:media/*:read.
    let p = principal(
        "user:alice",
        "acme",
        &["mcp:media.upload:call", "mcp:media.get:call"],
    );
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p, "acme", &id, 200)
        .await
        .unwrap();

    let err = media_serve(&store, &p, "acme", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::Denied));
}

// ── Mandatory: workspace isolation ───────────────────────────────────────────────────────────

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn media_not_visible_from_other_workspace() {
    let store = Store::memory().await.unwrap();
    let p_a = principal("user:alice", "acme", CAPS);
    let p_b = principal("user:carol", "globex", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p_a,
        "acme",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p_a, "acme", &id, 200)
        .await
        .unwrap();

    // ws-B can't see ws-A's media.
    let err = media_serve(&store, &p_b, "globex", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotFound));

    // ws-B's media list is empty.
    let list = media_list(&store, &p_b, "globex").await.unwrap();
    assert!(list.is_empty());
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn delete_archives_media() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "acme", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "acme",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "acme", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p, "acme", &id, 200)
        .await
        .unwrap();

    media_delete(&store, &p, "acme", &id).await.unwrap();

    let media = media_get(&store, &p, "acme", &id).await.unwrap();
    assert_eq!(media.status, lb_host::MediaStatus::Archived);

    // Archived media can't be served.
    let err = media_serve(&store, &p, "acme", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotReady));
}
