//! Media at the host layer: the chunked upload protocol, serve route, and variant derivation
//! (media scope). Tests the mandatory capability-deny, workspace isolation, resume after dropped
//! chunk, bad checksum, duplicate chunk idempotency, oversize rejection, variant derivation, and
//! ETag. Real store, real caps — no mocks (rule 9). Images are seeded real bytes.

use lb_auth::{mint, verify, Claims, Principal, Role, SigningKey};
use lb_host::{
    chunk_write, media_chunk_put, media_chunk_write, media_delete, media_get, media_list,
    media_read, media_serve, media_upload_begin, media_upload_commit, plan_serve, MediaError,
    ServePlan, CHUNK_SIZE, CHUNK_TABLE,
};
use lb_store::Store;
use sha2::{Digest, Sha256};

fn principal(sub: &str, ws: &str, caps: &[&str]) -> Principal {
    let key = SigningKey::generate();
    let claims = Claims {
        sub: sub.into(),
        ws: ws.into(),
        role: Role::Member,
        caps: caps.iter().map(|s| s.to_string()).collect(),
        iat: 0,
        exp: u64::MAX,
        constraint: None,
        run_id: None,
    };
    let token = mint(&key, &claims);
    verify(&key, &token, 1).expect("token verifies")
}

const CAPS: &[&str] = &[
    "mcp:media.upload:call",
    "mcp:media.get:call",
    "mcp:media.delete:call",
    "store:media/*:read",
];

fn checksum(bytes: &[u8]) -> String {
    let hash = Sha256::digest(bytes);
    hex(&hash)
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(char::from_digit((b >> 4) as u32, 16).unwrap());
        out.push(char::from_digit((b & 0xf) as u32, 16).unwrap());
    }
    out
}

/// A real 4x4 red PNG generated by the `image` crate (not a hand-crafted byte sequence).
fn tiny_png() -> Vec<u8> {
    let img = image::RgbImage::from_pixel(4, 4, image::Rgb([255, 0, 0]));
    let mut buf = Vec::new();
    image::DynamicImage::ImageRgb8(img)
        .write_to(&mut std::io::Cursor::new(&mut buf), image::ImageFormat::Png)
        .unwrap();
    buf
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn upload_and_serve_image() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    // Begin
    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    let chunks = begin["chunks"].as_u64().unwrap();
    assert_eq!(chunks, 1);

    // Upload chunk 0
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();

    // Commit
    let commit = media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();
    assert_eq!(commit["ok"], serde_json::json!(true));

    // Serve original
    let served = media_serve(&store, &p, "nube", &id, None).await.unwrap();
    assert_eq!(served.bytes, img);
    assert_eq!(served.mime, "image/png");

    // Serve thumb variant
    let thumb = media_serve(&store, &p, "nube", &id, Some("thumb"))
        .await
        .unwrap();
    assert_eq!(thumb.mime, "image/jpeg");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn duplicate_chunk_is_idempotent() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    // Write chunk 0 twice — idempotent.
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();

    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn bad_checksum_is_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        "wrong-checksum",
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();

    let err = media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::BadChecksum));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn oversize_rejected_at_begin() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);

    let err = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        999_999_999_999,
        "checksum",
        None,
        100,
    )
    .await
    .unwrap_err();
    assert!(matches!(err, MediaError::TooLarge));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn serve_not_ready_media_is_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    // Don't commit — media is still Uploading.
    let err = media_serve(&store, &p, "nube", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotReady));
}

// ── Mandatory: capability-deny ──────────────────────────────────────────────────────────────

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn denies_upload_without_cap() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:mallory", "nube", &["mcp:media.get:call"]);

    let err = media_upload_begin(&store, &p, "nube", "image/png", 100, "cs", None, 100)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::Denied));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn denies_serve_without_read_cap() {
    let store = Store::memory().await.unwrap();
    // Has upload cap but NOT store:media/*:read.
    let p = principal(
        "user:alice",
        "nube",
        &["mcp:media.upload:call", "mcp:media.get:call"],
    );
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    let err = media_serve(&store, &p, "nube", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::Denied));
}

// ── Mandatory: workspace isolation ───────────────────────────────────────────────────────────

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn media_not_visible_from_other_workspace() {
    let store = Store::memory().await.unwrap();
    let p_a = principal("user:alice", "nube", CAPS);
    let p_b = principal("user:carol", "globex", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p_a,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p_a, "nube", &id, 200)
        .await
        .unwrap();

    // ws-B can't see ws-A's media.
    let err = media_serve(&store, &p_b, "globex", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotFound));

    // ws-B's media list is empty.
    let list = media_list(&store, &p_b, "globex").await.unwrap();
    assert!(list.is_empty());
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn delete_archives_media() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    media_delete(&store, &p, "nube", &id).await.unwrap();

    let media = media_get(&store, &p, "nube", &id).await.unwrap();
    assert_eq!(media.status, lb_host::MediaStatus::Archived);

    // Archived media can't be served.
    let err = media_serve(&store, &p, "nube", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotReady));
}

// ── Validated chunk PUT (media_chunk_put — the gateway route's host verb) ────────────────────

/// Begin a small PNG upload; return (id, img bytes).
async fn begin_png(store: &Store, p: &Principal) -> (String, Vec<u8>) {
    let img = tiny_png();
    let cs = checksum(&img);
    let begin = media_upload_begin(
        store,
        p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    (begin["id"].as_str().unwrap().to_string(), img)
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn chunk_put_denied_without_upload_cap() {
    let store = Store::memory().await.unwrap();
    let owner = principal("user:alice", "nube", CAPS);
    let (id, img) = begin_png(&store, &owner).await;

    // Authenticated but uncapped: no mcp:media.upload:call → denied before any byte lands.
    let mallory = principal("user:mallory", "nube", &["mcp:media.get:call"]);
    let err = media_chunk_put(&store, &mallory, "nube", &id, 0, &img)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::Denied));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn chunk_put_unknown_upload_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let err = media_chunk_put(&store, &p, "nube", "no-such-upload", 0, b"bytes")
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotFound));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn chunk_put_after_ready_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let (id, img) = begin_png(&store, &p).await;
    media_chunk_put(&store, &p, "nube", &id, 0, &img)
        .await
        .unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    // Re-PUT after Ready would change served bytes while the ETag stayed stale — rejected.
    let err = media_chunk_put(&store, &p, "nube", &id, 0, b"tampered bytes")
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::BadInput(_)));

    // Served bytes are untouched.
    let served = media_serve(&store, &p, "nube", &id, None).await.unwrap();
    assert_eq!(served.bytes, img);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn chunk_put_out_of_range_n_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let (id, img) = begin_png(&store, &p).await; // 1-chunk upload
    let err = media_chunk_put(&store, &p, "nube", &id, 1, &img)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::BadInput(_)));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn chunk_put_oversize_body_rejected() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let (id, _img) = begin_png(&store, &p).await;
    let oversize = vec![0u8; CHUNK_SIZE as usize + 1];
    let err = media_chunk_put(&store, &p, "nube", &id, 0, &oversize)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::TooLarge));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn chunk_put_isolated_across_workspaces() {
    let store = Store::memory().await.unwrap();
    let p_a = principal("user:alice", "nube", CAPS);
    let p_b = principal("user:carol", "globex", CAPS);
    let (id, img) = begin_png(&store, &p_a).await;

    // A ws-B caller cannot write chunks into ws-A's upload (record invisible in globex).
    let err = media_chunk_put(&store, &p_b, "globex", &id, 0, &img)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::NotFound));
}

// ── Corrupt chunk row → hard error, never a truncated 200 ────────────────────────────────────

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn corrupt_chunk_row_is_a_serve_error() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let (id, img) = begin_png(&store, &p).await;
    media_chunk_put(&store, &p, "nube", &id, 0, &img)
        .await
        .unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    // Corrupt the chunk row directly in the store (real store, real row — rule 9).
    let chunk_id = format!("{id}:0");
    let corrupt = serde_json::json!({
        "media_id": id, "n": 0, "bytes": "%%%not-base64%%%", "len": img.len(),
    });
    lb_store::write(&store, "nube", CHUNK_TABLE, &chunk_id, &corrupt)
        .await
        .unwrap();

    // Serving must fail loudly (Store/Decode), never return truncated bytes with a 200.
    let err = media_serve(&store, &p, "nube", &id, None)
        .await
        .unwrap_err();
    assert!(matches!(err, MediaError::Store(_)), "got: {err}");
}

// ── Multi-chunk resume: out of order + re-upload + commit + serve ────────────────────────────

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn multi_chunk_out_of_order_resume_and_serve() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);

    // 2.5 MiB of deterministic non-trivial bytes → 3 chunks at the 1 MiB chunk size.
    let total = 2 * CHUNK_SIZE as usize + CHUNK_SIZE as usize / 2;
    let blob: Vec<u8> = (0..total).map(|i| (i % 251) as u8).collect();
    let cs = checksum(&blob);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "application/octet-stream",
        blob.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    assert_eq!(begin["chunks"].as_u64().unwrap(), 3);

    let chunk =
        |n: usize| &blob[n * CHUNK_SIZE as usize..(total.min((n + 1) * CHUNK_SIZE as usize))];

    // Upload out of order: 2, 0, 1 — then chunk 1 "times out" and is re-PUT (idempotent).
    media_chunk_put(&store, &p, "nube", &id, 2, chunk(2))
        .await
        .unwrap();
    media_chunk_put(&store, &p, "nube", &id, 0, chunk(0))
        .await
        .unwrap();
    media_chunk_put(&store, &p, "nube", &id, 1, chunk(1))
        .await
        .unwrap();
    media_chunk_put(&store, &p, "nube", &id, 1, chunk(1))
        .await
        .unwrap();

    // Commit verifies the checksum over the assembled bytes.
    let commit = media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();
    assert_eq!(commit["ok"], serde_json::json!(true));

    // Serve returns the full assembled blob.
    let served = media_serve(&store, &p, "nube", &id, None).await.unwrap();
    assert_eq!(served.bytes.len(), total);
    assert_eq!(served.bytes, blob);
}

// ── Conditional / Range serve planning (the gateway route's host logic) ──────────────────────

#[test]
fn if_none_match_matching_etag_is_304() {
    // The ETag the serve path emits is the quoted checksum; a matching If-None-Match → 304.
    assert_eq!(
        plan_serve(100, "\"abc123\"", Some("\"abc123\""), None),
        ServePlan::NotModified
    );
    // If-None-Match wins over Range (RFC 9110 evaluation order).
    assert_eq!(
        plan_serve(100, "\"abc123\"", Some("\"abc123\""), Some("bytes=0-9")),
        ServePlan::NotModified
    );
    // A stale ETag does not 304.
    assert_eq!(
        plan_serve(100, "\"abc123\"", Some("\"old\""), None),
        ServePlan::Full
    );
}

#[test]
fn range_plans_are_correct() {
    // Bounded range.
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=10-19")),
        ServePlan::Partial { start: 10, end: 19 }
    );
    // Open-ended + end clamped to len-1.
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=90-")),
        ServePlan::Partial { start: 90, end: 99 }
    );
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=90-500")),
        ServePlan::Partial { start: 90, end: 99 }
    );
    // Suffix range: last 10 bytes.
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=-10")),
        ServePlan::Partial { start: 90, end: 99 }
    );
    // Unsatisfiable: start beyond the body.
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=100-")),
        ServePlan::Unsatisfiable
    );
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=200-300")),
        ServePlan::Unsatisfiable
    );
    // Malformed / multi-range → full 200 (Range ignored).
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=abc")),
        ServePlan::Full
    );
    assert_eq!(
        plan_serve(100, "\"e\"", None, Some("bytes=0-9,20-29")),
        ServePlan::Full
    );
    assert_eq!(plan_serve(100, "\"e\"", None, None), ServePlan::Full);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn range_slice_matches_served_bytes() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let (id, img) = begin_png(&store, &p).await;
    media_chunk_put(&store, &p, "nube", &id, 0, &img)
        .await
        .unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    let served = media_serve(&store, &p, "nube", &id, None).await.unwrap();
    // A ranged GET for the first 8 bytes yields the PNG magic prefix.
    match plan_serve(
        served.bytes.len() as u64,
        &served.etag,
        None,
        Some("bytes=0-7"),
    ) {
        ServePlan::Partial { start, end } => {
            assert_eq!(&served.bytes[start as usize..=end as usize], &img[0..8]);
        }
        other => panic!("expected partial, got {other:?}"),
    }
    // And a matching If-None-Match against the real ETag plans a 304.
    assert_eq!(
        plan_serve(
            served.bytes.len() as u64,
            &served.etag,
            Some(&served.etag),
            None
        ),
        ServePlan::NotModified
    );
}

// ── `media.read` — bytes over the MCP bridge ────────────────────────────────────────────────────
//
// The verb exists for a caller that CANNOT set an `Authorization` header (a module-federated
// extension UI, mounted deliberately without the session token). These tests pin the two things
// that make it safe to hand bytes to that caller: it reaches nothing the serve route would not
// serve, and it stops at the workspace wall.

/// The round-trip: the base64 the verb returns decodes to exactly the bytes the serve route serves.
/// If these ever diverge, an extension renders a corrupt image with no error to trace.
#[tokio::test]
async fn read_returns_the_same_bytes_the_serve_route_would() {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;

    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    let out = media_read(&store, &p, "nube", &id, None, 0, None)
        .await
        .unwrap();

    let decoded = B64.decode(out["bytes"].as_str().unwrap()).unwrap();
    assert_eq!(
        decoded, img,
        "the bridge must deliver the file byte-for-byte"
    );
    assert_eq!(out["mime"], serde_json::json!("image/png"));
    assert_eq!(out["total"].as_u64().unwrap(), img.len() as u64);
    assert_eq!(out["offset"].as_u64().unwrap(), 0);
    assert!(
        out["eof"].as_bool().unwrap(),
        "a file this small arrives in one slice"
    );
}

/// The derived `thumb` variant is reachable the same way — this is the rendition a hero actually
/// wants, and the whole reason a UI would rather not pull the original.
#[tokio::test]
async fn read_serves_the_thumb_variant() {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;

    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    // Commit derives the thumbnail synchronously for an image.
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    let out = media_read(&store, &p, "nube", &id, Some("thumb"), 0, None)
        .await
        .unwrap();

    let decoded = B64.decode(out["bytes"].as_str().unwrap()).unwrap();
    assert!(!decoded.is_empty(), "the thumb variant must carry bytes");
    // Derived as JPEG regardless of the source mime (see `variant.rs`).
    assert_eq!(out["mime"], serde_json::json!("image/jpeg"));
}

/// **The capability wall.** `media.read` must reach nothing the serve route would refuse — it
/// delegates to `media_serve`, so the per-item `store:media/{id}:read` gate is the same one.
/// Without it, bytes over the bridge would be a way around the wall rather than a way through it.
#[tokio::test]
async fn read_is_denied_without_the_media_read_cap() {
    let store = Store::memory().await.unwrap();
    // Upload + metadata caps, but NOT `store:media/*:read`.
    let p = principal(
        "user:alice",
        "nube",
        &["mcp:media.upload:call", "mcp:media.get:call"],
    );
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    let err = media_read(&store, &p, "nube", &id, None, 0, None)
        .await
        .expect_err("reading bytes without the read cap must be refused");
    assert!(matches!(err, MediaError::Denied), "got {err:?}");
}

/// **Workspace isolation.** A photo uploaded in one workspace is unreachable from another — the
/// case the site-photo scope calls out explicitly, because testing only the annotation row would
/// pass while the bytes leaked.
#[tokio::test]
async fn read_does_not_cross_the_workspace_wall() {
    let store = Store::memory().await.unwrap();
    let alice = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &alice,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    chunk_write(&store, "nube", &id, 0, &img).await.unwrap();
    media_upload_commit(&store, &alice, "nube", &id, 200)
        .await
        .unwrap();

    // A principal in ANOTHER workspace, holding every media cap there.
    let mallory = principal("user:mallory", "other", CAPS);
    let err = media_read(&store, &mallory, "other", &id, None, 0, None)
        .await
        .expect_err("another workspace must not reach these bytes");
    assert!(
        matches!(err, MediaError::NotFound | MediaError::Denied),
        "got {err:?}"
    );
}

/// A file larger than one slice is walked with `offset`, and reassembles exactly. This is the loop
/// every caller writes, so the boundary it depends on is pinned against a real store.
#[tokio::test]
async fn a_multi_slice_file_reassembles_by_walking_offset() {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;

    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    // Larger than one CHUNK_SIZE so the media spans multiple stored chunks too.
    let blob: Vec<u8> = (0..(CHUNK_SIZE as usize + 4096))
        .map(|i| (i % 251) as u8)
        .collect();
    let cs = checksum(&blob);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "application/octet-stream",
        blob.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    let chunks = begin["chunks"].as_u64().unwrap() as u32;
    for n in 0..chunks {
        let start = (n as usize) * CHUNK_SIZE as usize;
        let end = ((start + CHUNK_SIZE as usize).min(blob.len())) as usize;
        chunk_write(&store, "nube", &id, n, &blob[start..end])
            .await
            .unwrap();
    }
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();

    // Walk it in 64 KiB slices, exactly as a UI would.
    let mut got: Vec<u8> = Vec::new();
    let mut offset = 0u64;
    let mut rounds = 0;
    loop {
        let out = media_read(&store, &p, "nube", &id, None, offset, Some(64 * 1024))
            .await
            .unwrap();
        got.extend(B64.decode(out["bytes"].as_str().unwrap()).unwrap());
        offset += out["len"].as_u64().unwrap();
        rounds += 1;
        assert!(rounds < 200, "the walk must terminate");
        if out["eof"].as_bool().unwrap() {
            break;
        }
    }

    assert_eq!(got, blob, "a walked file must reassemble byte-for-byte");
}

/// **The whole point, end to end.** An upload driven ENTIRELY over the MCP bridge — begin, chunks,
/// commit, read back — with no HTTP route touched at any step.
///
/// This is the path a module-federated extension UI must take, because it holds no bearer token and
/// therefore cannot call `PUT /media/{id}/chunk/{n}` or `GET /media/{id}`. If this test fails, the
/// only remaining way to upload a site photo from an extension is to lift the host's session token
/// out of `localStorage` — which is what these two verbs exist to make unnecessary.
#[tokio::test]
async fn an_upload_completes_entirely_over_the_bridge_without_http() {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;

    let store = Store::memory().await.unwrap();
    // Exactly the caps an extension would request: upload + read. No HTTP, no ambient session.
    let p = principal(
        "ext:pdnsw",
        "nube",
        &[
            "mcp:media.upload:call",
            "mcp:media.get:call",
            "store:media/*:read",
        ],
    );

    let img = tiny_png();
    let cs = checksum(&img);

    // 1. begin (MCP)
    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();
    let chunks = begin["chunks"].as_u64().unwrap() as u32;

    // 2. chunks (MCP, base64) — NOT the HTTP PUT route.
    for n in 0..chunks {
        let start = (n as usize) * CHUNK_SIZE as usize;
        let end = (start + CHUNK_SIZE as usize).min(img.len());
        let out = media_chunk_write(&store, &p, "nube", &id, n, &B64.encode(&img[start..end]))
            .await
            .unwrap();
        assert_eq!(out["ok"], serde_json::json!(true));
    }

    // 3. commit (MCP)
    let commit = media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();
    assert_eq!(
        commit["ok"],
        serde_json::json!(true),
        "the checksum must verify — bytes that arrived over the bridge are the same bytes"
    );

    // 4. read back (MCP) and confirm it is byte-identical to what we uploaded.
    let out = media_read(&store, &p, "nube", &id, None, 0, None)
        .await
        .unwrap();
    assert_eq!(B64.decode(out["bytes"].as_str().unwrap()).unwrap(), img);
}

/// A re-write of the same chunk is idempotent over the bridge too — the property the HTTP route
/// already has, and the one a flaky connection depends on.
#[tokio::test]
async fn a_re_written_chunk_is_idempotent_over_the_bridge() {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;

    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    let b64 = B64.encode(&img);
    media_chunk_write(&store, &p, "nube", &id, 0, &b64)
        .await
        .unwrap();
    // Same chunk again — a retry after a dropped response.
    media_chunk_write(&store, &p, "nube", &id, 0, &b64)
        .await
        .unwrap();

    // The commit still verifies: the re-write upserted rather than appending.
    media_upload_commit(&store, &p, "nube", &id, 200)
        .await
        .unwrap();
    let served = media_serve(&store, &p, "nube", &id, None).await.unwrap();
    assert_eq!(served.bytes, img);
}

/// Malformed base64 is refused with a reason naming the field, rather than reaching the store as
/// truncated bytes that only fail later at checksum time.
#[tokio::test]
async fn a_chunk_that_is_not_base64_is_refused_with_the_reason() {
    let store = Store::memory().await.unwrap();
    let p = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &p,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    let err = media_chunk_write(&store, &p, "nube", &id, 0, "not!valid!base64!")
        .await
        .expect_err("malformed base64 must be refused");
    match err {
        MediaError::BadInput(m) => assert!(m.contains("base64"), "got {m}"),
        other => panic!("expected BadInput, got {other:?}"),
    }
}

/// The upload cap gates the bridge path exactly as it gates the HTTP one — this verb must not be a
/// way around `mcp:media.upload:call`.
#[tokio::test]
async fn chunk_write_is_denied_without_the_upload_cap() {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;

    let store = Store::memory().await.unwrap();
    let uploader = principal("user:alice", "nube", CAPS);
    let img = tiny_png();
    let cs = checksum(&img);

    let begin = media_upload_begin(
        &store,
        &uploader,
        "nube",
        "image/png",
        img.len() as u64,
        &cs,
        None,
        100,
    )
    .await
    .unwrap();
    let id = begin["id"].as_str().unwrap().to_string();

    // A principal with READ caps but no upload cap.
    let reader = principal("user:bob", "nube", &["mcp:media.get:call"]);
    let err = media_chunk_write(&store, &reader, "nube", &id, 0, &B64.encode(&img))
        .await
        .expect_err("writing chunks without the upload cap must be refused");
    assert!(matches!(err, MediaError::Denied), "got {err:?}");
}
