//! Catalog rows for the `time` family — one row per `register_fn` site in this folder (the
//! catalog maintenance rule). Append-only; overloads (the two `format` arities) get one row each.

use crate::catalog::FnEntry;

pub(crate) const CATALOG: &[FnEntry] = &[
    FnEntry {
        name: "time.now",
        family: "time",
        signature: "time.now() -> int",
        description: "The run's logical clock, unix seconds (never a wall-clock; stable across a resume).",
    },
    FnEntry {
        name: "time.now_ms",
        family: "time",
        signature: "time.now_ms() -> int",
        description: "The run's logical clock, unix milliseconds.",
    },
    FnEntry {
        name: "time.iso",
        family: "time",
        signature: "time.iso(ts: int) -> String",
        description: "Format unix seconds as an RFC-3339 UTC instant (\"2026-07-04T03:21:00Z\").",
    },
    FnEntry {
        name: "time.iso_ms",
        family: "time",
        signature: "time.iso_ms(ts_ms: int) -> String",
        description: "Format unix milliseconds as an RFC-3339 UTC instant with millisecond precision.",
    },
    FnEntry {
        name: "time.date",
        family: "time",
        signature: "time.date(ts: int) -> String",
        description: "The UTC calendar date of a timestamp (\"2026-07-04\").",
    },
    FnEntry {
        name: "time.clock",
        family: "time",
        signature: "time.clock(ts: int) -> String",
        description: "The UTC time-of-day of a timestamp (\"03:21:00\").",
    },
    FnEntry {
        name: "time.format",
        family: "time",
        signature: "time.format(ts: int, fmt: String, offset?: String) -> String",
        description: "strftime-format a timestamp in UTC, or at an explicit fixed offset (\"+10:00\"/\"-05:30\").",
    },
    FnEntry {
        name: "time.parse",
        family: "time",
        signature: "time.parse(s: String) -> int",
        description: "Parse RFC-3339/ISO-8601 (or an epoch-secs/-ms numeric string) to unix seconds.",
    },
    FnEntry {
        name: "time.parse_fmt",
        family: "time",
        signature: "time.parse_fmt(s: String, fmt: String) -> int",
        description: "strptime-parse a string with an explicit format to unix seconds (UTC unless the format carries an offset).",
    },
    FnEntry {
        name: "time.from_ymd",
        family: "time",
        signature: "time.from_ymd(y: int, m: int, d: int) -> int",
        description: "Build a timestamp from a UTC calendar date at midnight.",
    },
    FnEntry {
        name: "time.from_parts",
        family: "time",
        signature: "time.from_parts(y: int, m: int, d: int, h: int, mi: int, s: int) -> int",
        description: "Build a timestamp from full UTC date + time components (each range-checked).",
    },
    FnEntry {
        name: "time.year",
        family: "time",
        signature: "time.year(ts: int) -> int",
        description: "The UTC calendar year of a timestamp.",
    },
    FnEntry {
        name: "time.month",
        family: "time",
        signature: "time.month(ts: int) -> int",
        description: "The UTC month of a timestamp (1-12).",
    },
    FnEntry {
        name: "time.day",
        family: "time",
        signature: "time.day(ts: int) -> int",
        description: "The UTC day-of-month of a timestamp (1-31).",
    },
    FnEntry {
        name: "time.hour",
        family: "time",
        signature: "time.hour(ts: int) -> int",
        description: "The UTC hour of a timestamp (0-23).",
    },
    FnEntry {
        name: "time.minute",
        family: "time",
        signature: "time.minute(ts: int) -> int",
        description: "The UTC minute of a timestamp (0-59).",
    },
    FnEntry {
        name: "time.second",
        family: "time",
        signature: "time.second(ts: int) -> int",
        description: "The UTC second of a timestamp (0-59).",
    },
    FnEntry {
        name: "time.weekday",
        family: "time",
        signature: "time.weekday(ts: int) -> int",
        description: "The ISO weekday of a timestamp (1=Monday … 7=Sunday).",
    },
    FnEntry {
        name: "time.weekday_name",
        family: "time",
        signature: "time.weekday_name(ts: int) -> String",
        description: "The English weekday name of a timestamp (\"Friday\").",
    },
    FnEntry {
        name: "time.day_of_year",
        family: "time",
        signature: "time.day_of_year(ts: int) -> int",
        description: "The ordinal day of the year (1-366).",
    },
    FnEntry {
        name: "time.iso_week",
        family: "time",
        signature: "time.iso_week(ts: int) -> int",
        description: "The ISO-8601 week number of a timestamp (1-53).",
    },
    FnEntry {
        name: "time.days_in_month",
        family: "time",
        signature: "time.days_in_month(ts: int) -> int",
        description: "How many days the timestamp's UTC month has (leap-aware).",
    },
    FnEntry {
        name: "time.is_leap_year",
        family: "time",
        signature: "time.is_leap_year(ts: int) -> bool",
        description: "Whether the timestamp's UTC year is a leap year.",
    },
    FnEntry {
        name: "time.is_weekend",
        family: "time",
        signature: "time.is_weekend(ts: int) -> bool",
        description: "Whether the timestamp falls on a UTC Saturday or Sunday.",
    },
    FnEntry {
        name: "time.start_of_day",
        family: "time",
        signature: "time.start_of_day(ts: int) -> int",
        description: "Floor a timestamp to UTC midnight of its day.",
    },
    FnEntry {
        name: "time.start_of_week",
        family: "time",
        signature: "time.start_of_week(ts: int) -> int",
        description: "Floor a timestamp to UTC midnight of its ISO week's Monday.",
    },
    FnEntry {
        name: "time.start_of_month",
        family: "time",
        signature: "time.start_of_month(ts: int) -> int",
        description: "Floor a timestamp to UTC midnight of the 1st of its month.",
    },
    FnEntry {
        name: "time.start_of_year",
        family: "time",
        signature: "time.start_of_year(ts: int) -> int",
        description: "Floor a timestamp to UTC midnight of Jan 1 of its year.",
    },
    FnEntry {
        name: "time.end_of_day",
        family: "time",
        signature: "time.end_of_day(ts: int) -> int",
        description: "The last second of the timestamp's UTC day (23:59:59).",
    },
    FnEntry {
        name: "time.end_of_month",
        family: "time",
        signature: "time.end_of_month(ts: int) -> int",
        description: "The last second of the timestamp's UTC month (leap-aware).",
    },
    FnEntry {
        name: "time.add",
        family: "time",
        signature: "time.add(ts: int, dur: String) -> int",
        description: "Add a duration in the s/m/h/d/w form (\"24h\") to a timestamp.",
    },
    FnEntry {
        name: "time.sub",
        family: "time",
        signature: "time.sub(ts: int, dur: String) -> int",
        description: "Subtract a duration in the s/m/h/d/w form (\"7d\") from a timestamp.",
    },
    FnEntry {
        name: "time.floor",
        family: "time",
        signature: "time.floor(ts: int, dur: String) -> int",
        description: "Align a timestamp DOWN to its epoch-aligned bucket (matches rollup buckets).",
    },
    FnEntry {
        name: "time.ceil",
        family: "time",
        signature: "time.ceil(ts: int, dur: String) -> int",
        description: "Align a timestamp UP to the next epoch-aligned bucket boundary (on-boundary stays put).",
    },
    FnEntry {
        name: "time.diff",
        family: "time",
        signature: "time.diff(a: int, b: int) -> int",
        description: "The signed difference a - b in seconds.",
    },
    FnEntry {
        name: "time.diff_days",
        family: "time",
        signature: "time.diff_days(a: int, b: int) -> int",
        description: "The signed difference a - b in whole days (truncated).",
    },
    FnEntry {
        name: "time.since",
        family: "time",
        signature: "time.since(ts: int) -> int",
        description: "Seconds elapsed from ts to the run's logical now (negative if ts is in the future).",
    },
    FnEntry {
        name: "time.until",
        family: "time",
        signature: "time.until(ts: int) -> int",
        description: "Seconds from the run's logical now to ts (negative if ts is in the past).",
    },
    FnEntry {
        name: "time.ago",
        family: "time",
        signature: "time.ago(ts: int) -> String",
        description: "Humanize a timestamp relative to now (\"3h 20m ago\", future -> \"in 3h 20m\") for message bodies.",
    },
];
