//! The function allow-list for a scoped read. Deny by default: a function not named here (or in the
//! policy's `extra_functions`) is refused, because some functions run SQL text or read state outside
//! the row rewrite — `query_to_xml`, `dblink`, `set_config`/`current_setting`, `pg_*`, `lo_*`.
//! Everything here is a pure computation over its arguments.

const ALLOWED: &[&str] = &[
    // aggregates
    "count",
    "sum",
    "avg",
    "min",
    "max",
    "stddev",
    "stddev_samp",
    "stddev_pop",
    "variance",
    "var_samp",
    "var_pop",
    "bool_and",
    "bool_or",
    "every",
    "array_agg",
    "string_agg",
    "json_agg",
    "jsonb_agg",
    "json_object_agg",
    "jsonb_object_agg",
    "mode",
    "percentile_cont",
    "percentile_disc",
    "corr",
    "covar_pop",
    "covar_samp",
    "regr_slope",
    "regr_intercept",
    "regr_r2",
    "regr_count",
    "bit_and",
    "bit_or",
    // window
    "row_number",
    "rank",
    "dense_rank",
    "percent_rank",
    "cume_dist",
    "ntile",
    "lag",
    "lead",
    "first_value",
    "last_value",
    "nth_value",
    // conditional + math
    "coalesce",
    "nullif",
    "greatest",
    "least",
    "abs",
    "ceil",
    "ceiling",
    "floor",
    "round",
    "trunc",
    "sign",
    "sqrt",
    "cbrt",
    "power",
    "pow",
    "exp",
    "ln",
    "log",
    "log10",
    "mod",
    "div",
    "width_bucket",
    "pi",
    "degrees",
    "radians",
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "atan2",
    "num_nulls",
    "num_nonnulls",
    "isfinite",
    // strings
    "lower",
    "upper",
    "length",
    "char_length",
    "character_length",
    "octet_length",
    "concat",
    "concat_ws",
    "substring",
    "substr",
    "left",
    "right",
    "trim",
    "btrim",
    "ltrim",
    "rtrim",
    "replace",
    "split_part",
    "strpos",
    "position",
    "lpad",
    "rpad",
    "initcap",
    "repeat",
    "reverse",
    "translate",
    "starts_with",
    "regexp_replace",
    "regexp_match",
    "regexp_matches",
    "regexp_split_to_array",
    "regexp_like",
    "md5",
    "to_char",
    "to_number",
    "format",
    "quote_literal",
    "quote_ident",
    "chr",
    "ascii",
    // date / time
    "now",
    "date_trunc",
    "date_part",
    "date_bin",
    "extract",
    "to_timestamp",
    "to_date",
    "age",
    "make_date",
    "make_time",
    "make_timestamp",
    "make_timestamptz",
    "make_interval",
    "justify_hours",
    "justify_days",
    "justify_interval",
    "timezone",
    "clock_timestamp",
    "statement_timestamp",
    "transaction_timestamp",
    "current_date",
    "current_timestamp",
    "localtimestamp",
    // TimescaleDB analytics
    "time_bucket",
    "time_bucket_gapfill",
    "locf",
    "interpolate",
    "first",
    "last",
    "histogram",
    // json
    "json_build_object",
    "jsonb_build_object",
    "json_build_array",
    "jsonb_build_array",
    "to_json",
    "to_jsonb",
    "json_extract_path",
    "jsonb_extract_path",
    "json_extract_path_text",
    "jsonb_extract_path_text",
    "json_array_length",
    "jsonb_array_length",
    "jsonb_typeof",
    "json_typeof",
    "jsonb_strip_nulls",
    "row_to_json",
    // arrays
    "array_length",
    "array_position",
    "array_positions",
    "cardinality",
    "array_to_string",
    "string_to_array",
    "array_remove",
    "array_append",
    "array_prepend",
    "array_cat",
    "array_upper",
    "array_lower",
    // set-returning (also allowed in FROM, see `set_returning`)
    "generate_series",
    "unnest",
];

const SET_RETURNING: &[&str] = &["generate_series", "unnest"];

/// May a scoped read call function `name` (already folded to its bare, lowercase name)?
pub(super) fn allowed(name: &str, extras: &[String]) -> bool {
    ALLOWED.contains(&name) || extras.iter().any(|e| e == name)
}

/// May a scoped read use `name` as a FROM item?
pub(super) fn set_returning(name: &str) -> bool {
    SET_RETURNING.contains(&name)
}
