// GENERATED by `cargo run -p lb-prefs --bin gen-prefs-catalog`. DO NOT EDIT.
// The built-in MF1 message catalogs — the single source shared with the Rust host.
// The client parses these with intl-messageformat; the host with its MF1 subset
// parser. Byte-identity with the host `.mf` assets is drift-tested.

export type BuiltinCatalog = {
  version: string;
  messages: Record<string, string>;
};

export const BUILTIN_CATALOGS: Record<string, BuiltinCatalog> = {
  "en": {
    version: "1",
    messages: {
      "alert.items_pending": "You have {count, plural, =0{no pending items} one{# pending item} other{# pending items}}",
      "alert.severity": "{level, select, critical{Critical alert} warning{Warning} other{Notice}}: {detail}",
      "alert.threshold_crossed": "{name} exceeded {limit, quantity, speed} at {ts, date}",
      "invite.email.body": "You have been invited to workspace {workspace}. Click the link to accept: /accept?token={token}",
      "invite.email.subject": "You are invited to join {workspace}",
      "notify.new_messages": "{name} sent you {count, plural, one{a message} other{# messages}}",
      "notify.welcome": "Welcome, {name}!",
      "report.reading": "Reading: {value, quantity, temperature} recorded at {ts, date}",
    },
  },
  "es": {
    version: "1",
    messages: {
      "alert.items_pending": "Tienes {count, plural, =0{ningún elemento pendiente} one{# elemento pendiente} other{# elementos pendientes}}",
      "alert.severity": "{level, select, critical{Alerta crítica} warning{Advertencia} other{Aviso}}: {detail}",
      "alert.threshold_crossed": "{name} superó {limit, quantity, speed} el {ts, date}",
      "invite.email.body": "Has sido invitado al espacio de trabajo {workspace}. Haz clic en el enlace para aceptar: /accept?token={token}",
      "invite.email.subject": "Te han invitado a unirte a {workspace}",
      "notify.new_messages": "{name} te envió {count, plural, one{un mensaje} other{# mensajes}}",
      "notify.welcome": "¡Bienvenido, {name}!",
      "report.reading": "Lectura: {value, quantity, temperature} registrada el {ts, date}",
    },
  },
};
