// GENERATED by `cargo run -p lb-prefs --bin gen-prefs-ts`. DO NOT EDIT.
// The closed prefs vocabulary — the single source of truth shared with the server.

export const DIMENSIONS = [
  "temperature",
  "speed",
  "distance",
  "mass",
  "pressure",
  "data",
  "percent",
  "time",
] as const;
export type Dimension = (typeof DIMENSIONS)[number];

export const UNITS = [
  "celsius",
  "fahrenheit",
  "kelvin",
  "meter_per_second",
  "kilometer_per_hour",
  "mile_per_hour",
  "knot",
  "meter",
  "kilometer",
  "foot",
  "mile",
  "kilogram",
  "gram",
  "pound",
  "ounce",
  "pascal",
  "hectopascal",
  "bar",
  "psi",
  "byte",
  "kilobyte",
  "megabyte",
  "gigabyte",
  "ratio",
  "percent",
  "second",
  "minute",
  "hour",
  "day",
] as const;
export type Unit = (typeof UNITS)[number];

export const UNIT_DIMENSION: Record<Unit, Dimension> = {
  "celsius": "temperature",
  "fahrenheit": "temperature",
  "kelvin": "temperature",
  "meter_per_second": "speed",
  "kilometer_per_hour": "speed",
  "mile_per_hour": "speed",
  "knot": "speed",
  "meter": "distance",
  "kilometer": "distance",
  "foot": "distance",
  "mile": "distance",
  "kilogram": "mass",
  "gram": "mass",
  "pound": "mass",
  "ounce": "mass",
  "pascal": "pressure",
  "hectopascal": "pressure",
  "bar": "pressure",
  "psi": "pressure",
  "byte": "data",
  "kilobyte": "data",
  "megabyte": "data",
  "gigabyte": "data",
  "ratio": "percent",
  "percent": "percent",
  "second": "time",
  "minute": "time",
  "hour": "time",
  "day": "time",
};

export const DATE_STYLES = ["eu", "iso", "usa"] as const;
export const TIME_STYLES = ["h12", "h24"] as const;
export const UNIT_SYSTEMS = ["metric", "imperial"] as const;
export const NUMBER_FORMATS = ["dot_comma", "comma_dot", "space_comma"] as const;
export const FIRST_DAYS = ["monday", "sunday"] as const;
export const ENABLED_LANGUAGES = ["en", "es"] as const;
