// Component test for the one-screen converter UI (grafana-conv scope, "Testing
// plan" → "UI (shadcn/Tauri)"). Stubs `fetch` to return the REAL mapper output
// captured in `./sample-output.json` (regenerated by
// `cargo run -p grafana-conv-mapper --example emit_fixture > sample-output.json`).
//
// This is not a fake backend — the data is real mapper output, captured. The
// per-claim contract (panels → cells, the report's honesty lines) lives in the
// Rust golden tests; this test asserts the UI renders that real output: the
// converted dashboard and the report's three fate groups.

import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { App } from "./App";
import realOutput from "./test/sample-output.json";

describe("App", () => {
  beforeEach(() => {
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => ({
        ok: true,
        status: 200,
        json: async () => realOutput,
      })),
    );
  });

  it("converts the input and renders the dashboard output + report", async () => {
    const user = userEvent.setup();
    render(<App />);

    // The sample is pre-filled; drive the conversion.
    await user.click(screen.getByText("Convert"));

    // The converted dashboard renders in the output pane (scope to the output
    // pre — the sample is also in the input textarea).
    const outputPre = document.querySelector("pre");
    expect(outputPre?.textContent).toContain('"title": "Sample"');

    // The report renders all three fate groups (mapped / degraded / dropped) with
    // their real counts from the captured mapper output.
    const mapped = realOutput.report.mapped.length;
    const degraded = realOutput.report.degraded.length;
    const dropped = realOutput.report.dropped.length;
    expect(screen.getByText(`Mapped: ${mapped}`)).toBeInTheDocument();
    expect(screen.getByText(`Degraded: ${degraded}`)).toBeInTheDocument();
    expect(screen.getByText(`Dropped: ${dropped}`)).toBeInTheDocument();

    // The honesty contract: a dropped feature has a named line (editable=false).
    expect(screen.getByText(/dashboards are always editable/)).toBeInTheDocument();
  });

  it("shows a parse error for invalid JSON", async () => {
    const user = userEvent.setup();
    render(<App />);
    const ta = screen.getByPlaceholderText(/Drop a Grafana/i) as HTMLTextAreaElement;
    await user.clear(ta);
    // Set value directly — `user.type` interprets `{` as a keyboard macro.
    fireEvent.change(ta, { target: { value: "{not json" } });
    await user.click(screen.getByText("Convert"));
    expect(await screen.findByText(/invalid JSON/i)).toBeInTheDocument();
  });
});
