//! The generated client catalog must match the checked-in file (i18n-catalogs scope: "a drift test
//! re-runs the generator and asserts the on-disk client file is byte-identical"). Host and client
//! catalogs are the *same bytes* by construction, so drift fails here rather than shipping a skewed
//! release. Regenerate with:
//!   `cargo run -p lb-prefs --bin gen-prefs-catalog > ../ui/src/lib/prefs/catalog.generated.ts`
//!
//! The generator's `render()` is recomputed here from the same public API (no process spawn), the
//! shipped `generated_ts_test` pattern.

use lb_prefs::catalog::{parse_builtin, EN_MF, ES_MF};

/// Mirror of `bin/gen_catalog::render` — kept here so the test does not depend on the bin crate.
fn render() -> String {
    let mut s = String::new();
    s.push_str("// GENERATED by `cargo run -p lb-prefs --bin gen-prefs-catalog`. DO NOT EDIT.\n");
    s.push_str(
        "// The built-in MF1 message catalogs — the single source shared with the Rust host.\n",
    );
    s.push_str(
        "// The client parses these with intl-messageformat; the host with its MF1 subset\n",
    );
    s.push_str("// parser. Byte-identity with the host `.mf` assets is drift-tested.\n\n");
    s.push_str("export type BuiltinCatalog = {\n");
    s.push_str("  version: string;\n");
    s.push_str("  messages: Record<string, string>;\n");
    s.push_str("};\n\n");
    s.push_str("export const BUILTIN_CATALOGS: Record<string, BuiltinCatalog> = {\n");
    for (lang, src) in [("en", EN_MF), ("es", ES_MF)] {
        let cat = parse_builtin(src);
        s.push_str(&format!("  {lang:?}: {{\n"));
        s.push_str(&format!("    version: {:?},\n", cat.version));
        s.push_str("    messages: {\n");
        for (key, msg) in &cat.messages {
            s.push_str(&format!("      {key:?}: {msg:?},\n"));
        }
        s.push_str("    },\n");
        s.push_str("  },\n");
    }
    s.push_str("};\n");
    s
}

#[test]
fn checked_in_catalog_matches_generator() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../ui/src/lib/prefs/catalog.generated.ts"
    );
    let on_disk = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "generated catalog missing at {path}: {e} — run `cargo run -p lb-prefs --bin gen-prefs-catalog`"
        )
    });
    assert_eq!(
        on_disk,
        render(),
        "generated client catalog is stale — regenerate catalog.generated.ts"
    );
}

#[test]
fn builtins_parse_and_share_keys() {
    // Both builtins parse, carry the same version, and are key-for-key aligned (so the es→en
    // fallback is total — no en key is missing an es counterpart or vice versa).
    let en = parse_builtin(EN_MF);
    let es = parse_builtin(ES_MF);
    assert_eq!(en.version, "1");
    assert_eq!(es.version, "1");
    assert!(!en.messages.is_empty());
    assert_eq!(
        en.messages.keys().collect::<Vec<_>>(),
        es.messages.keys().collect::<Vec<_>>(),
        "en and es builtins must share the same key set"
    );
}
