//! The generated client constants must match the checked-in file (prefs scope: "client and server
//! can't disagree on the allowed set"). This test re-runs the generator and asserts the
//! `ui/src/lib/prefs/dimensions.generated.ts` on disk is byte-identical — a drift fails here rather
//! than shipping a stale unit picker. Regenerate with:
//!   `cargo run -p lb-prefs --bin gen-prefs-ts > ../ui/src/lib/prefs/dimensions.generated.ts`
//!
//! The generator's `render()` is exercised via the binary's module; we recompute it here from the
//! same public axis API to keep the test self-contained (no process spawn).

use lb_prefs::axis::{DateStyle, Dimension, FirstDay, NumberFormat, TimeStyle, Unit, UnitSystem};

/// Mirror of `bin/gen_ts::render` — kept here so the test does not depend on the bin crate. If the
/// two ever diverge the checked-in file test below catches it (both derive from the same enums).
fn render() -> String {
    let mut s = String::new();
    s.push_str("// GENERATED by `cargo run -p lb-prefs --bin gen-prefs-ts`. DO NOT EDIT.\n");
    s.push_str(
        "// The closed prefs vocabulary — the single source of truth shared with the server.\n\n",
    );
    s.push_str("export const DIMENSIONS = [\n");
    for d in Dimension::ALL {
        s.push_str(&format!("  {:?},\n", d.as_str()));
    }
    s.push_str("] as const;\n");
    s.push_str("export type Dimension = (typeof DIMENSIONS)[number];\n\n");
    s.push_str("export const UNITS = [\n");
    for u in Unit::ALL {
        s.push_str(&format!("  {:?},\n", u.as_str()));
    }
    s.push_str("] as const;\n");
    s.push_str("export type Unit = (typeof UNITS)[number];\n\n");
    s.push_str("export const UNIT_DIMENSION: Record<Unit, Dimension> = {\n");
    for u in Unit::ALL {
        s.push_str(&format!(
            "  {:?}: {:?},\n",
            u.as_str(),
            u.dimension().as_str()
        ));
    }
    s.push_str("};\n\n");
    s.push_str(&string_const(
        "DATE_STYLES",
        DateStyle::ALL.iter().map(|x| x.as_str()),
    ));
    s.push_str(&string_const(
        "TIME_STYLES",
        TimeStyle::ALL.iter().map(|x| x.as_str()),
    ));
    s.push_str(&string_const(
        "UNIT_SYSTEMS",
        UnitSystem::ALL.iter().map(|x| x.as_str()),
    ));
    s.push_str(&string_const(
        "NUMBER_FORMATS",
        NumberFormat::ALL.iter().map(|x| x.as_str()),
    ));
    s.push_str(&string_const(
        "FIRST_DAYS",
        FirstDay::ALL.iter().map(|x| x.as_str()),
    ));
    s.push_str(&string_const(
        "ENABLED_LANGUAGES",
        lb_prefs::ENABLED_LANGUAGES.iter().copied(),
    ));
    s
}

fn string_const<'a>(name: &str, values: impl Iterator<Item = &'a str>) -> String {
    let items: Vec<String> = values.map(|v| format!("{v:?}")).collect();
    format!("export const {name} = [{}] as const;\n", items.join(", "))
}

#[test]
fn checked_in_ts_matches_generator() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../ui/src/lib/prefs/dimensions.generated.ts"
    );
    let on_disk = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "generated TS missing at {path}: {e} — run `cargo run -p lb-prefs --bin gen-prefs-ts`"
        )
    });
    assert_eq!(
        on_disk,
        render(),
        "generated client constants are stale — regenerate dimensions.generated.ts"
    );
}

#[test]
fn dimension_and_unit_counts_match_declared_all() {
    // Guard the ALL arrays against an enum variant added without updating ALL (the generator + every
    // exhaustive test reads ALL).
    assert_eq!(Dimension::ALL.len(), 8);
    assert_eq!(Unit::ALL.len(), 29);
    for u in Unit::ALL {
        assert_eq!(
            Unit::parse(u.as_str()),
            Some(u),
            "every unit token round-trips through parse"
        );
    }
}
