//! The `ros` **connection** verbs — CRUD over the connection config shadow + `ros.ping`. A connection
//! is one reachable ROS appliance (`base_url` + an `External` token). The token is taken on
//! `create`/`update`, stashed via `lb-secrets`, and NEVER returned by `get`/`list` or logged (it is
//! not even stored in the shadow — see `shadow.rs`). Each verb self-checks its capability first.

use serde_json::{json, Value};

use super::{page_args, req_str};
use crate::host::{HostCtx, HostError};
use crate::paging::keyset_page;
use crate::resolve::{delete_token, set_token, RosApiFactory};
use crate::shadow::{delete_ros, get_ros, list_ros, put_ros, RosShadow};

/// A connection as returned to a caller — the shadow, guaranteed token-free (the shadow has no token
/// field, so this is the shadow verbatim; the type documents the guarantee at the boundary).
fn public_view(shadow: &RosShadow) -> Value {
    json!({
        "uuid": shadow.uuid,
        "name": shadow.name,
        "base_url": shadow.base_url,
        "enable": shadow.enable,
        "poll_rate": shadow.poll_rate,
    })
}

/// `ros.list` — keyset-paged connections in the workspace (token-free).
pub async fn list(host: &HostCtx, input: &Value) -> Result<Value, HostError> {
    host.require("ros.list")?;
    let (cursor, limit) = page_args(input);
    let shadows = list_ros(host).await?;
    let views: Vec<Value> = shadows.iter().map(public_view).collect();
    Ok(keyset_page(views, cursor.as_deref(), limit, |v| {
        v["uuid"].as_str().unwrap_or_default().to_string()
    }))
}

/// `ros.get` — one connection by uuid (token never returned). A missing uuid is a clean not-found.
pub async fn get(host: &HostCtx, input: &Value) -> Result<Value, HostError> {
    host.require("ros.get")?;
    let uuid = req_str(input, "uuid")?;
    match get_ros(host, &uuid).await? {
        Some(shadow) => Ok(public_view(&shadow)),
        None => Ok(json!({ "error": "not_found", "uuid": uuid })),
    }
}

/// `ros.create` — register an appliance `{name, base_url, token}`. Stores the shadow (`enable:true`),
/// stashes the token via `lb-secrets`, returns the `ros_uuid`. The uuid is caller-supplied for
/// idempotency (a re-create with the same uuid overwrites) or generated by the caller.
pub async fn create(host: &HostCtx, input: &Value, ts: u64) -> Result<Value, HostError> {
    host.require("ros.create")?;
    let uuid = req_str(input, "uuid")?;
    let name = req_str(input, "name")?;
    let base_url = req_str(input, "base_url")?;
    let token = req_str(input, "token")?;

    let shadow = RosShadow {
        uuid: uuid.clone(),
        name,
        base_url,
        enable: input
            .get("enable")
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        poll_rate: input.get("poll_rate").and_then(|v| v.as_u64()),
        parent: None,
    };
    // Shadow first, then the token — a token without a shadow is orphaned, the reverse is a
    // connection that simply can't authenticate yet (recoverable by an update).
    put_ros(host, &shadow, ts).await?;
    set_token(host, &uuid, &token).await?;
    Ok(json!({ "uuid": uuid }))
}

/// `ros.update` — rename / re-point / toggle `enable` (the poll-silence lever) / re-token. Only the
/// supplied fields change; a `token` (if present) is re-stashed and never echoed back.
pub async fn update(host: &HostCtx, input: &Value, ts: u64) -> Result<Value, HostError> {
    host.require("ros.update")?;
    let uuid = req_str(input, "uuid")?;
    let mut shadow = match get_ros(host, &uuid).await? {
        Some(s) => s,
        None => return Ok(json!({ "error": "not_found", "uuid": uuid })),
    };

    if let Some(name) = input.get("name").and_then(|v| v.as_str()) {
        shadow.name = name.to_string();
    }
    if let Some(base_url) = input.get("base_url").and_then(|v| v.as_str()) {
        shadow.base_url = base_url.to_string();
    }
    if let Some(enable) = input.get("enable").and_then(|v| v.as_bool()) {
        shadow.enable = enable;
    }
    if let Some(poll_rate) = input.get("poll_rate").and_then(|v| v.as_u64()) {
        shadow.poll_rate = Some(poll_rate);
    }
    put_ros(host, &shadow, ts).await?;

    if let Some(token) = input.get("token").and_then(|v| v.as_str()) {
        set_token(host, &uuid, token).await?;
    }
    Ok(public_view(&shadow))
}

/// `ros.delete` — remove a connection (shadow + its secret token).
pub async fn delete(host: &HostCtx, input: &Value) -> Result<Value, HostError> {
    host.require("ros.delete")?;
    let uuid = req_str(input, "uuid")?;
    delete_ros(host, &uuid).await?;
    // Best-effort token cleanup: if the shadow was already gone the secret may be too; a missing
    // secret on delete is not an error worth failing the whole delete over.
    let _ = delete_token(host, &uuid).await;
    Ok(json!({ "ok": true, "uuid": uuid }))
}

/// `ros.ping` — health-check the appliance (proxies `/api/system/ping` through the resolved client).
pub async fn ping(
    host: &HostCtx,
    factory: &dyn RosApiFactory,
    input: &Value,
) -> Result<Value, HostError> {
    host.require("ros.ping")?;
    let uuid = req_str(input, "uuid")?;
    let api = match crate::resolve::resolve_api(host, factory, &uuid).await? {
        Some(api) => api,
        None => return Ok(json!({ "error": "not_found", "uuid": uuid })),
    };
    match api.ping().await {
        Ok(p) => Ok(json!({ "ok": true, "health": p.health, "ros": p.ros })),
        Err(e) => Ok(json!({ "ok": false, "error": e.to_string() })),
    }
}
